def command_output(command):
    database=[['Acne','doxycycline',' Acne, also known as acne vulgaris, is a skin condition involving clogged pores. Triggered by puberty, hormones, and improved nutrition, affecting younger ages. Increasingly seen in adults, especially women. Dead skin cells and oil combine, clogging pores, leading to blackheads, whiteheads, pimples, or cysts. Hormones in puberty trigger sebum production, combining with dead cells. Family history, hormones, environment, and medications contribute to risk. Symptoms include various types of bumps on face, back, chest, and shoulders. Severe cases warrant dermatologist consultation for prescription treatments. Good skin care, gentle cleansing, topical and oral medications, and lifestyle adjustments are key. Benzoyl peroxide, salicylic acid, retinoids, antibiotics, and others are common treatments. Prevention involves regular cleansing, avoiding picking, protecting skin from sun and tanning. Early dermatologist consultation can prevent scarring.'],
['ADHD','Vyvanse',' ADHD (Attention Deficit Hyperactivity Disorder) is a common behavioral disorder in children and adolescents. Subgroups: inattentive, hyperactive/impulsive, and combined. Symptoms vary in severity and frequency; often misdiagnosed in girls with inattentive characteristics. Causes include genetics, family history, brain injury, lead exposure, low birth weight, and environmental factors. No evidence of links to parenting, food, sugar, or vaccinations. Diagnosis involves discussions with doctors, considering emotional control, attentiveness, relationships, and hyperactivity. ADHD is usually diagnosed around age 78 but can begin earlier. Behavioral education is firstline treatment, especially for mild cases or young children. Pharmacological treatments include atomoxetine, amphetamine/dextroamphetamine, methylphenidate, clonidine, and guanfacine.'],
['AIDS/HIV','Truvada',' HIV (Human Immunodeficiency Virus) targets CD4 cells, weakening the immune system and potentially leading to AIDS (Acquired Immunodeficiency Syndrome). Originated from chimpanzee virus, mutated in late 1800s; detected in the US since the mid1970s. Transmitted sexually, through blood contact, pregnancy, childbirth, or breastfeeding. Highrisk behaviors include unprotected sex, needle sharing, and certain medical procedures. Initial acute HIV symptoms include fever, headache, rash, sore throat, and swollen lymph nodes. Clinical latent infection follows with minimal symptoms; can last around 10 years. Symptomatic HIV infection brings fatigue, weight loss, infections, and swollen lymph nodes. Untreated HIV often progresses to AIDS in about 10 years, marked by low CD4 count and opportunistic infections. Antiretroviral therapy (ART) doesnt cure HIV but significantly slows its progression. ART involves combinations of nucleoside/nucleotide reverse transcriptase inhibitors, nonnucleoside reverse transcriptase inhibitors, protease inhibitors, fusion inhibitors, CCR5 antagonists, postattachment inhibitors, and integrase strand transfer inhibitors. ART reduces transmission risk and allows people with HIV to lead relatively healthy lives.'],
['Allergies','hydroxyzine',' Allergies are immune system overreactions to harmless substances, called allergens or triggers. Immune system mistakes allergens as threats, producing antibodies and releasing histamine. Common allergens include animal fur, dust mites, food (milk, eggs, peanuts, etc.), insect stings, latex, medicines, mold, and pollen. Allergy symptoms vary: skin reactions, itching, rash, sneezing, runny/stuffy nose, wheezing, coughing, shortness of breath. Severe reactions, anaphylaxis, can cause loss of consciousness, low blood pressure, severe shortness of breath, skin rash, rapid pulse. Persistent or severe allergies interfering with daily life warrant medical attention. Anaphylaxis requires immediate use of an epinephrine autoinjector and a visit to the emergency department. Treatments include antihistamines, corticosteroids, decongestants, saline nasal rinses, and immunotherapy. Allergy sufferers should avoid triggers, wear medical alert bracelets, and seek medical advice for effective management.'],
['Alzheimers','Aricept',' Alzheimers Disease is a progressive neurodegenerative disorder affecting cognitive functions. Nerve cell loss and dysfunction in various brain areas lead to memory and language impairments. Exact cause of nerve cell death is uncertain, but abnormal protein filaments in cells are observed. Also known as Presenile Dementia, Senile Dementia Alzheimers Type (SDAT). Cognitive decline includes memory loss, language problems, disorientation, poor judgment. Advanced stages lead to loss of ability to care for oneself, requiring fulltime assistance. Risk factors include age, family history, genetics, and certain lifestyle factors. No cure exists, but treatments can alleviate symptoms and slow progression in some cases. Early diagnosis crucial for effective management. Research continues to understand the diseases mechanisms and develop better treatments.'],
['Angina','aspirin',' Angina pectoris is chest pain or discomfort due to coronary heart disease. Its a symptom of myocardial ischemia, where the heart muscle doesnt receive enough blood (oxygen). Caused by narrowed or blocked coronary arteries, leading to insufficient blood supply (ischemia). Also known as Angina, Angina Pectoris, Heart Pains, and categorized into different types based on stability. Typical angina presents as pressure, fullness, squeezing, or pain in the chest center. Discomfort can radiate to the neck, jaw, shoulder, back, or arm. Other conditions like acid reflux and lung issues can cause similar chest discomfort not related to angina.'],
['Anxiety','Xanax',' Anxiety is an emotion marked by tension, worried thoughts, and physical symptoms like sweating and increased heart rate. Its a normal response, but excessive or persistent anxiety may be diagnosed as an anxiety disorder. Anxiety is part of the bodys fightorflight response to perceived threats. Anxiety disorders can arise from various triggers including family, health, money, work, and substance withdrawal. Symptoms include disproportionate worry, physical sensations, irritability, restlessness, fatigue, and sleep problems. Generalized Anxiety Disorder (GAD) involves chronic excessive worry about everyday life, often accompanied by physical symptoms. Other anxiety disorders include panic disorder, phobias, social anxiety disorder, and more. Treatment varies based on the severity and type of anxiety disorder, including stress management, therapy, counseling, medication, and lifestyle changes.'],
['Asthma','Singulair',' Asthma is an inflammatory airway disorder causing recurrent attacks of wheezing, shortness of breath, chest tightness, and coughing. Also known as Bronchial Asthma, Exerciseinduced Asthma, Wheezing. Inflammation leads to narrowing of airways, making breathing difficult. Triggers include allergens, respiratory infections, cold air, exercise, smoke, and strong odors. Common symptoms during asthma attacks: wheezing (whistling sound while breathing), difficulty breathing, chest tightness, coughing. Symptoms vary in intensity and frequency; some may have chronic symptoms. Severity categorized as intermittent, mild persistent, moderate persistent, and severe persistent. Can affect anyone, often starting in childhood; family history, genetics, and environmental factors play a role. No cure, but managed through medication, inhalers, and avoiding triggers. Longterm management aims to control symptoms and prevent exacerbations. Quickrelief medications provide immediate relief during attacks, while longterm controllers reduce inflammation and prevent symptoms. Regular monitoring and communication with a healthcare provider are essential for effective management.'],
['Bipolar Disorder','Lamictal',' Bipolar disorder, also known as manic depression, is a mood disorder characterized by fluctuating episodes of depression and mania. Different types include bipolar I, bipolar II, cyclothymic disorder, mixed features, and rapidcycling disorder. Symptoms vary based on the type of episode: manic episodes involve high energy, impulsiveness, and sometimes psychosis; depressive episodes feature low mood, hopelessness, and lack of interest. Hypomania is a milder form of mania, and some individuals experience it without fullblown mania. Genetic factors play a role, and stressors can trigger episodes. Misdiagnosis as depression is common; correct diagnosis is essential for appropriate treatment. Treatment includes mood stabilizers, antipsychotics, and sometimes antidepressants, combined with therapy like cognitivebehavioral therapy (CBT). Managing routines, sleep, and involving family in treatment can be helpful. Medication and therapy are often used in combination for effective management.'],
['Bronchitis','Mucinex',' Bronchitis is an inflammation of the bronchial tubes, which are the air passages in the lungs. It is often caused by viruses, similar to those causing colds or the flu, but bacterial infections can also contribute. Risk factors include smoking, weak immune system, exposure to irritants like dust or chemicals, and living in polluted areas. Symptoms include persistent cough, increased mucus production, fatigue, chest discomfort, and shortness of breath. Acute bronchitis typically follows a cold or flu and usually resolves within a few weeks, while chronic bronchitis may persist for months or years. Diagnosis involves physical examination, lung auscultation, and sometimes chest Xrays or pulmonary function tests. Antibiotics are usually not effective for viral bronchitis; treatment focuses on symptom relief, such as cough medications, bronchodilators, and corticosteroids for those with other respiratory conditions. Nonpharmacological treatments like warm drinks, humidifiers, and avoiding irritants can help alleviate symptoms. Chronic bronchitis is associated with smoking and can be part of chronic obstructive pulmonary disease (COPD). Seeking medical attention is necessary if symptoms are severe, persistent, bloodtinged cough, or accompanied by fever, wheezing, or shortness of breath.'],
['Cancer','carboplatin',' Cancer is a term used for a group of diseases characterized by the uncontrolled growth and spread of abnormal cells. It can affect any part of the body and can originate from various types of cells, leading to different types of cancer. Cancerous cells can invade nearby tissues and organs, and they can also spread to other parts of the body through the bloodstream or lymphatic system. The growth of cancer cells is caused by mutations in the DNA within cells, which can be caused by various factors including genetics, exposure to carcinogens (cancercausing substances), radiation, certain infections, and lifestyle factors. Common types of cancer include breast cancer, lung cancer, prostate cancer, colorectal cancer, and skin cancer. Cancer symptoms can vary widely depending on the type and stage of cancer, but they often include fatigue, unexplained weight loss, pain, changes in skin, persistent coughing, and more. Early detection is crucial for successful treatment; many cancers are easier to treat when caught in their early stages. Diagnostic methods include imaging tests (Xrays, CT scans, MRI), biopsies (tissue sampling), and blood tests to detect specific markers. Treatment options include surgery, radiation therapy, chemotherapy, targeted therapy, immunotherapy, and hormone therapy, often used in combination. The choice of treatment depends on factors such as the type and stage of cancer, as well as the patients overall health. Cancer treatment aims to remove or destroy cancer cells, shrink tumors, and prevent the cancer from spreading or returning.'],
['Cholesterol','atorvastatin',' High cholesterol, also known as hypercholesterolemia, refers to elevated levels of cholesterol, triglycerides, and lipoproteins in the blood. It is often categorized as an acquired lipid disorder, involving an abnormal increase in fatty substances circulating in the bloodstream. Familial hypercholesterolemia is a genetic condition that leads to exceptionally high cholesterol levels from birth. Elevated cholesterol levels contribute to the buildup of plaque in arteries, a condition known as atherosclerosis. Atherosclerosis increases the risk of heart disease, stroke, and other cardiovascular complications. Factors like genetics, poor diet, sedentary lifestyle, obesity, and certain medical conditions contribute to high cholesterol. High cholesterol usually doesnt cause noticeable symptoms, making regular screenings important for detection. Diagnosis involves a blood test measuring cholesterol levels, including LDL (bad cholesterol) and HDL (good cholesterol). Lifestyle changes play a crucial role in managing high cholesterol, including adopting a hearthealthy diet, exercising regularly, and maintaining a healthy weight. In some cases, medication like statins may be prescribed to lower cholesterol levels. Preventive measures include avoiding smoking, reducing saturated and trans fats intake, and limiting processed foods. High cholesterol is a significant risk factor for cardiovascular diseases, which are leading causes of death globally. Managing cholesterol levels helps in reducing the risk of heartrelated complications and improving overall health.'],
['Colds & Flu','Benadryl',' Cold symptoms, also known as the common cold or coryza, result from viral infections in the upper respiratory tract. These symptoms include nasal congestion, runny nose, sneezing, coughing, sore throat, and mild fatigue. Common colds are caused mainly by rhinoviruses and are shortlasting, usually around 35 days. The immune response to the virus leads to inflammation, mucus production, and these symptoms. Colds are highly contagious and spread through droplets and contact. Rest, hydration, and overthecounter meds can help alleviate discomfort. Antibiotics dont work against cold viruses. Preventive measures like handwashing and avoiding close contact can reduce spread. If symptoms are severe or prolonged, consult a healthcare professional.'],
['Constipation','docusate',' Constipation is difficulty or infrequency in passing feces (poo) and is characterized by less frequent bowel movements than normal. Causes of constipation include a lack of fiber or fluid in the diet, slow bowel movements due to various factors like disease, medications, or hormonal changes. Symptoms of constipation include dry, hard, lumpy stools, straining during bowel movements, and a feeling of incomplete emptying. Complications of untreated constipation can include anal fissures, hemorrhoids, fecal impaction, and rectal prolapse. Diagnosis involves a medical evaluation, especially if symptoms are severe, accompanied by pain, blood in stools, or unexplained weight loss. Treatment includes dietary changes with increased fiber and fluid intake, regular exercise, and overthecounter laxatives. Laxatives come in various forms like bulkforming, emollient stool softeners, osmotic, and stimulant laxatives. Lifestyle modifications like avoiding constipationcausing foods, staying hydrated, and being physically active can help prevent constipation.'],
['COPD','Symbicort',' COPD (Chronic Obstructive Pulmonary Disease) is a group of lung diseases characterized by limited airflow and varying degrees of air sac enlargement and lung tissue destruction. Common forms of COPD include emphysema and chronic bronchitis. Emphysema involves the destruction of lung tissue, particularly the air sacs, reducing their elasticity and causing breathing difficulties. Chronic bronchitis is marked by inflammation of the bronchial tubes, leading to excessive mucus production, coughing, and narrowing of airways. COPD is often caused by smoking, but longterm exposure to irritants like air pollution, dust, and chemicals can also contribute. Symptoms include shortness of breath, chronic cough, wheezing, and chest tightness. COPD symptoms usually develop gradually and worsen over time, leading to reduced lung function. Diagnosing COPD involves lung function tests like spirometry and imaging tests like chest Xrays. COPD is a chronic, progressive condition that cant be completely reversed, but its progression can be slowed and symptoms managed. Treatment includes quitting smoking, medications like bronchodilators and inhaled corticosteroids, pulmonary rehabilitation, and oxygen therapy. Lifestyle changes such as staying physically active, maintaining a healthy diet, and avoiding lung irritants are important in managing COPD. In severe cases, lung transplantation may be considered.'],
['Covid 19','ivermectin',' COVID19 is caused by the SARSCoV2 virus. Common symptoms include fever, cough, and breathing difficulties. It spreads primarily through respiratory droplets and contaminated surfaces. Prevention measures include wearing masks, physical distancing, and hand hygiene. Vaccines have been developed and authorized for immunity against the virus. New variants of the virus have emerged over time. The pandemic has had significant global health, economic, and social impacts.'],
['Depression','bupropion',' Depression involves intense, persistent sadness. Causes: genetics, brain chemistry, stress, medical conditions, meds. Risk: women, older adults, chronic health issues, major life events, grief, meds, substances. Symptoms: lasting low mood, hopelessness, irritability, anxiety, social withdrawal, sleep/eating changes, physical complaints, risky behavior, selfharm, suicidal thoughts. Diagnosis: talk to a doctor, referral to psychiatrist possible. Treatment: therapy, antidepressants, response time varies. Selfhelp: coping skills, goals, crisis management, positive relationships, changing negative thoughts.'],
['Diabetes (Type 1)','Humalog',' Type 1 diabetes, also called Insulin Dependent Diabetes, Juvenile Onset Diabetes, or Type 1 Diabetes Mellitus, is a chronic condition.  It occurs due to the pancreas producing too little insulin to manage blood glucose levels effectively. Insulin is a hormone needed to regulate the uptake of glucose from the blood into cells. The immune system mistakenly attacks the insulinproducing cells in the pancreas. This leads to a lack of insulin, causing high blood sugar (hyperglycemia). Common symptoms include excessive thirst, frequent urination, unexplained weight loss, increased hunger, fatigue, and blurred vision Diagnosis involves blood tests to measure glucose levels and check for specific antibodies. People with type 1 diabetes need insulin therapy to control their blood sugar levels. Insulin can be administered through injections or insulin pumps. Regular monitoring of blood sugar levels is essential to adjust insulin doses. Dietary management involves balancing carbohydrate intake with insulin doses. Physical activity and a healthy lifestyle play a significant role in managing type 1 diabetes.'],
['Diabetes (Type 2)','metformin','Type 2 diabetes: Most common form. High blood glucose levels.Insulin: Often produced. Insufficient or resisted by cells (insulin resistance).Risk factors: Common in middleaged and older individuals. Obesity, especially in younger people. Ethnicities and sedentary lifestyle increase risk.Symptoms: Gradual and subtle onset. Thirst, hunger, frequent urination, infections, fatigue, blurred vision.Diagnosis: Screened in specific age groups and pregnant women. Blood tests: glucose levels, fasting or fingerprick. Examination, blood pressure, and cholesterol checks.Complications: High blood sugar damages vessels, nerves. Risks: heart attack, stroke, erectile dysfunction, foot issues, gum, eye, and kidney problems.Treatment: Essential for complication prevention. Medications, insulin therapies.'],
['Diarrhea','loperamide',' Diarrhea is characterized by loose, watery, and frequent bowel movements. When this condition persists for more than four weeks, its termed chronic diarrhea. Common symptoms include frequent watery stools. Causes of diarrhea can range from infections (bacterial, viral, parasitic) and food intolerances to medications, inflammatory conditions, and underlying health problems. Diarrhea can lead to dehydration due to the loss of fluids from the body. Additional symptoms may include cramping, abdominal pain, bloating, nausea, and fever, depending on the underlying cause. Some forms of diarrhea, particularly infectious ones, can be contagious. Diagnosis involves evaluating symptoms, medical history, travel history, and conducting tests like stool analysis. Treatment depends on the cause and can include fluid replacement, dietary adjustments, medications, and addressing infections. Practicing good hygiene, especially handwashing, can help prevent the spread of infectious diarrhea. Seek medical attention if diarrhea is severe, longlasting, associated with high fever, blood in stools, or signs of dehydration. Children and the elderly are at greater risk of complications due to dehydration from diarrhea. Travelers diarrhea can occur when visiting regions with different bacteria and parasites. Chronic diarrhea may be a symptom of underlying gastrointestinal conditions like irritable bowel syndrome (IBS) or inflammatory bowel disease (IBD).'],
['Eczema','triamcinolone',' Eczema, also called atopic eczema or dermatitis, is a skin condition affecting all age groups. The conditions severity varies, ranging from mild to severe. Mild eczema presents as dry, hot, and itchy skin. Severe cases involve broken, raw skin that can bleed. Eczema is not contagious, despite its appearance. Treatment can reduce inflammation, but the skin remains sensitive to flareups, requiring ongoing care. Even with treatment, the skin tends to stay sensitive and may need extra attention.'],
['Erectile Dysfunction','Cialis',' Erectile Dysfunction (ED) is the inability to maintain an erection sufficient for sexual intercourse. Its also known as impotence or male sexual dysfunction. The term "erectile dysfunction" is used medically to differentiate it from other sexual issues. Symptoms include difficulty achieving or sustaining an erection. Physical (vascular, hormonal) and psychological factors (stress, anxiety) contribute to ED. ED is common and affects men of different ages. Treatment varies based on the cause and may involve lifestyle changes, medications, therapy, or surgery.'],
['Gastrointestinal','Entereg',' Gastrointestinal Surgery is a medical field focusing on treating diseases, injuries, and deformities through physical operations or manipulations related to the stomach and intestines. It involves surgical interventions to address issues affecting the gastrointestinal tract. Gastrointestinal Surgery plays a crucial role in managing various conditions, such as cancers, ulcers, inflammatory bowel diseases, and obstructions. Surgical techniques range from minimally invasive procedures (laparoscopic surgery) to open surgeries, depending on the complexity of the case. Skilled surgeons perform gastrointestinal surgeries to remove tumors, repair damaged organs, address complications, and improve digestive functions. Recovery and outcomes vary based on the specific procedure, patients health, and adherence to postoperative care instructions. Collaborative care with gastroenterologists and other specialists is often required to ensure comprehensive treatment for gastrointestinal disorders.'],
['GERD (Heartburn)','omeprazole',' GERD, also called acid reflux or heartburn, involves stomach contents flowing back into the esophagus. This refluxed material is often acidic and can irritate the esophageal lining. Common symptoms include heartburn, regurgitation, chest pain, swallowing difficulties, and sour taste. GERD is chronic and occurs when the lower esophageal sphincter (LES) doesnt close properly. Causes include obesity, pregnancy, certain foods, smoking, and medical conditions. If left untreated, GERD can lead to complications like esophagitis and increased cancer risk. Diagnosis involves symptom assessment and tests like endoscopy and pH monitoring. Treatment includes lifestyle changes, antacids, prescription medications, and, in severe cases, surgery. Longterm management aims to control symptoms and prevent complications. Consult a healthcare professional if experiencing persistent GERD symptoms for proper diagnosis and management.'],
['Gout','allopurinol',' Gout is a type of arthritis affecting small joints, most commonly the big toe, causing swelling, tenderness, redness, and pain. Movement becomes difficult, and pain peaks in hours during an attack. Historical association with wealth due to rich diets, but modern research shows gout isnt linked to wealth. Gout results from uric acid crystals forming in joints, triggering an immune response and causing swelling and intense pain. Risk factors include gender (men), specific diets (high purine, processed foods), certain ethnicities, alcohol consumption, medical conditions, medications, and treatments. Diagnosis is important to prevent complications like joint damage, kidney stones, and tophi formation. Treatment involves medicines for acute attacks (NSAIDs, colchicine, corticosteroids) and for prevention (allopurinol, febuxostat, pegloticase, probenecid). Targeting uric acid levels below 6.0mg/dL is common in treatment. Lifestyle changes like avoiding sugary drinks and alcohol, staying hydrated, consuming lowfat dairy, reducing purinerich foods, exercising, and managing weight help prevent future attacks.'],
['Hair Loss','spironolactone',' Alopecia refers to hair loss or baldness. It can be named alopecia areata, balding, baldness, or female pattern baldness. Chemotherapyinduced hair loss occurs due to treatment but is usually temporary. Radiationinduced hair loss happens after head radiation and is generally permanent.'],
['Hayfever','Zyrtec',' Also known as hay fever or nasal allergies. Symptoms primarily affect the nose and eyes. Triggered by exposure to airborne particles like dust, dander, or pollen. Common symptoms include sneezing, runny or stuffy nose, and itchy or watery eyes. Seasonal and perennial types exist based on pollen exposure. Often coexists with allergies and asthma. Linked to environmental factors like pollen, dust mites, pet dander, and mold spores. Diagnosis involves symptoms assessment and sometimes allergy testing. Management includes trigger avoidance, medications (antihistamines, decongestants, nasal corticosteroids), and allergen immunotherapy.'],
['Herpes','acyclovir',' Herpes Simplex is caused by herpes viruses 1 or 2, affecting the mouth or genital area. Medications target symptoms and include purine nucleosides and topical antivirals. Herpes Simplex outbreaks can be managed using lysine. Various drug classes are available, including purine nucleosides, topical antiinfectives, and miscellaneous topical agents. Consultation with a healthcare professional is recommended for proper treatment. Use of certain medications may have positive or adverse effects, which users rate on a scale of effectiveness. Medications may be prescriptiononly (Rx) or available overthecounter (OTC). Drug scheduling, ranging from CSA Schedule 1 to Schedule 5, indicates potential for abuse and accepted medical use. Some medications may interact with alcohol.'],
['Hypertension','lisinopril',' High blood pressure, also called hypertension, occurs when blood pressure is above normal. Blood pressure measurements reflect heart efficiency in pumping blood. Blood pressure comprises systolic and diastolic readings. Systolic pressure indicates heart force against blood vessel resistance. Diastolic pressure measures heart resting between beats. Normal blood pressure is about 120/80 mm Hg, and ideally, below 130/80 mm Hg. High blood pressure has no noticeable symptoms in most cases. Untreated high blood pressure can damage blood vessels, increase stroke or heart attack risk, weaken the heart, and cause other complications. Diagnosis requires multiple high readings, avoiding triggers before measurement. Lifestyle changes recommended for slightly elevated blood pressure include weight loss, balanced diet, exercise, reducing salt and saturated fats, limiting alcohol.'],
['Hypothyroidism','levothyroxine',' Underactive thyroid is known as hypothyroidism. Thyroid gland produces insufficient hormones, affecting metabolism and body functions. Thyroid controls metabolism, energy use, and body temperature. Low thyroid levels slow metabolism, heart rate, and calorie burn. Common symptoms include sensitivity to cold, slow heart rate, fatigue, dry hair, weight gain, changes in menstrual cycle, depression, and more. Congenital hypothyroidism affects newborns, causing poor feeding, sleepiness, constipation, and growth issues. Diagnosis involves doctor examination, blood tests measuring thyroid hormones and serum TSH, and other tests such as cholesterol. Treatment involves replacing missing thyroid hormones with synthetic thyroid hormones. Levothyroxine, liothyronine, and liotrix are oral medications used. Regular blood tests ensure correct dosage, which can vary among individuals. Pregnant women might require higher dosages during pregnancy. Foods and medications can affect absorption and levels of replacement thyroid hormones.'],
['IBD (Bowel)','budesonide',' Also known as IBD, includes conditions like Crohns disease. Crohns disease is a chronic autoimmune disease. It can affect any part of the gastrointestinal tract. Commonly occurs in the ileum, where the small and large intestine meet.'],
['Incontinence','oxybutynin',' Incontinence is inability to control urine passage, ranging from occasional leakage to complete inability to hold urine. Three main types:   Stress incontinence: Occurs during activities like coughing, sneezing, or exercise due to weakened pelvic muscles or urethral sphincter.   Urge incontinence: Involves strong, sudden need to urinate, involuntary loss of urine, often more common in women and the elderly.   Mixed incontinence: Combines elements of stress and urge incontinence. Stress incontinence may result from weakened pelvic muscles or malfunction of the urethral sphincter. Urge incontinence involves instant bladder contraction after strong urge, often with no identifiable cause. Mixed incontinence contains features of both stress and urge incontinence. Treatment for stress incontinence: Behavioral changes, medication, pelvic floor muscle training, or surgery. Treatment for urge incontinence: Medication, retraining, or surgery. Mixed incontinence presents with features of both stress and urge incontinence.'],
['Insomnia','trazodone',' Also called difficulty sleeping, dyssomnia, inability to sleep, sleeplessness, or wakefulness. Insomnia refers to inability to sleep and abnormal wakefulness.'],
['Menopause','esterified estrogens / methyltestosterone',' Also known as Change of Life or Climacteric. Menopausal Disorders occur during menopause, a natural transition from regular menstrual periods to none. Menopause involves ovaries producing fewer eggs, reduced estrogen and progesterone levels. Hormone changes during menopause cause various disorders, including:   Mood changes   Hot flashes   Insomnia   Pounding or racing heart   Changes in sexual and urinary function.'],
['Migraine','sumatriptan',' Also known as Basilar Artery Migraine, BasilarType Migraine, Complicated Migraine, or Hemiplegic Migraine. Migraine headaches are recurring headaches with distinct features. Different from other headaches due to associated symptoms like nausea, vomiting, sensitivity to light. Some experience warning symptoms called aura before the headache. Not everyone gets aura; many experience migraines without warning.'],
['Osteoarthritis','meloxicam',' Also known as Degenerative Arthritis, Degenerative joint disease, DJD, Gonarthrosis, Hypertrophic Osteoarthritis, Joint Pain, OA, Osteoarthrosis, Sacroiliac Arthritis. Painful joint condition becoming more common with age. Caused by breakdown of cartilage in joints. Cartilage provides smooth motion and cushions bones; its loss causes friction and reduced shock absorption. Inflammatory processes worsen cartilage damage, leading to bone spurs and joint damage. Factors contributing to osteoarthritis include obesity, injuries, weak muscles, and genetics. Commonly affects hands, knees, hips, and spine. Symptoms include joint pain, stiffness, limited range of movement, swelling, clicking/cracking sounds, pain after activity. Diagnosis involves physical examination, history, blood tests, joint aspiration, Xrays, and MRI. Treatment includes exercise, weight loss, orthotics, heat/cold therapy, medications (acetaminophen, NSAIDs, capsaicin, duloxetine), cortisone injections, lubricating injections. Surgical options like osteotomy or joint replacement may be considered in severe cases.'],
['Osteoporosis','alendronate','Osteoporosis Other names: Bone Thinning Osteoporosis is the thinning of bone tissue and loss of bone density over time.'],
['Pain','tramadol','Pain An unpleasant sensory and emotional experience associated with actual or potential tissue damage or described in terms of such damage.'],
['Pneumonia','levofloxacin','Pneumonia Other names: Bronchopneumonia; Communityacquired pneumonia Pneumonia is an inflammation of the lungs caused by a bacterial, viral, or fungal infection.'],
['Psoriasis','clobetasol',' Also known as Erythrodermic Psoriasis, Guttate Psoriasis, Inverse Psoriasis, Palmoplantar Psoriasis. Common skin inflammation characterized by redness, itching, and thick, dry, silvery scales. Common medications include Humira and methotrexate.'],
['Rheumatoid Arthritis','methotrexate',' Also known as Arthritis, Arthritis, Rheumatoid, RA. Longterm inflammatory condition affecting joints and other tissues. Autoimmune condition where immune system attacks body tissues. Risk factors: smoking, hormones, family history. Symptoms: joint pain, swelling, stiffness, particularly in small joints. Stiffness worse in the morning, persists throughout the day. Joints may appear swollen, feel hot and tender. Nodules, firm swellings under the skin, can develop. Energy loss, fevers, sweating, poor appetite, weight loss. Diagnosis through physical exam, blood tests, Creactive protein, Rheumatoid Factor test, Xrays, MRI. Treatment: Medications, physical therapy, targeted exercises, health education, and surgery. Early and aggressive treatment can delay joint destruction.'],
['Schizophrenia','Seroquel',' Also known as Catatonic Schizophrenia, Disorganized Schizophrenia, Paranoid Schizophrenia, Residual Schizophrenia, Schizophrenia (catatonic, disorganized, paranoid, residual), Undifferentiated Schizophrenia. Serious brain disorder affecting perception, thinking, emotions, and behavior. Difficulty distinguishing between real and unreal experiences. Impaired logical thinking and emotional responses. Disruption in social interactions and behaviors.'],
['Seizures','Keppra',' Also known as Absence Seizure, Complex Partial Seizure, Fits. Seizure or convulsion is a sudden, uncontrolled contraction of muscles. Can manifest as violent muscle contractions or subtle moments of altered consciousness. Some seizures may involve "loss of contact" or daydreaminglike episodes.'],
['Stroke','Plavix',' Also known as Cerebrovascular Accident, CVA, Stroke. Ischemic stroke is caused by a blocked blood vessel in the brain. Blood clot blocks blood flow, leading to lack of oxygen and nutrients to brain cells. Prolonged blockage causes brain cell death and permanent damage.'],
['Swine Flu','Tamiflu',' Also known as H1N1 Influenza, Novel H1N1 Flu. Originates as a respiratory disease in pigs caused by type A influenza virus. Can cause outbreaks in pigs and occasionally infects humans. Symptoms similar to regular human seasonal influenza: fever, lethargy, lack of appetite, coughing. Additional symptoms may include runny nose, sore throat, nausea, vomiting, and diarrhea. Virus is contagious and can spread from human to human.'],
['UTI','ciprofloxacin',' UTI stands for Urinary Tract Infection. Caused by bacteria, such as Escherichia coli, Klebsiella pneumoniae, or Staphylococcus saprophyticus. Affects the urinary tract, including bladder, kidneys, ureters, and urethra. Women are at higher risk due to shorter urethra; older males also at risk. Risk factors include sexual intercourse, certain contraceptives, wiping back to front, kidney/bladder stones, urinary catheter, etc. Children can get UTIs too, with higher risk of kidney damage. Common symptoms of bladder infection (cystitis) include burning during urination, frequent urination, and pelvic pain. Kidney infections are more severe and may cause fever, cloudy/foulsmelling urine, back pain, nausea, etc. Bladder infections treated with antibiotics; kidney infections may require hospitalization for intravenous antibiotics. Prevention includes staying hydrated, urinating when needed, wiping front to back, urinating before/after sex, avoiding douches and scented products, and wearing comfortable clothing.'],
['Weight Loss','phentermine',' More than half of the U.S. population is overweight. Obesity is different from being overweight, defined by excess weight over maximum desirable for height. Obesity is when weight is 20% (25% in women) or more above the desirable range. Morbid obesity is when an adult is more than 100 pounds overweight. Obesity is defined by a BMI (body mass index) over 30 kg/m². Overweight is defined by a BMI between 25 and 29.9, not reaching obesity levels. Diet and calories play a significant role in weight management.'],
]
    
    command=command.lower()
    lstsplit=command.split()
    flag =0
    if "medicine" in command:
        for i in range(len(database)):
            for j in range(0,len(database[i][0])):
                if lstsplit[-1]==database[i][0].lower():
                    flag=1 
                    return (database[i][1],database[i][2])
    elif "condition" in command:
        for i in range(len(database)):
            for j in range(0,len(database[i][0])):
                if lstsplit[-1]==database[i][0].lower():
                    flag=1 
                    return (database[i][1],database[i][2])
    elif "conditions" in command:
        for i in range(len(database)):
            for j in range(0,len(database[i][0])):
                if lstsplit[-1]==database[i][0].lower():
                    flag=1 
                    return (database[i][1],database[i][2])
    else:
        for i in range(len(database)):
            for j in range(0,len(database[i][0])):
                if lstsplit[-1]==database[i][0].lower():
                    flag=1
                    return (database[i][1],database[i][2])
                
     
    nokey=("No Medicine Available","No idea about the conditions")
    if flag==0:
        return nokey
