def command_output(command):
    database=[['Acne','doxycycline'],
    ['ADHD','Vyvanse'],
    ['AIDS/HIV','Truvada'],
    ['Allergies','hydroxyzine'],
    ['Alzheimer','Aricept'],
    ['Angina','aspirin'],
    ['Anxiety','Xanax'],
    ['Asthma','Singulair'],
    ['Bipolar Disorder','Lamictal'],
    ['Bronchitis','Mucinex'],
    ['Cancer','carboplatin'],
    ['Cholesterol','atorvastatin'],
    ['Colds & Flu','Benadryl'],
    ['Constipation','docusate'],
    ['COPD','Symbicort'],
    ['Covid 19','ivermectin'],
    ['Depression','bupropion'],
    ['Diabetes (Type 1)','Humalog'],
    ['Diabetes (Type 2)','metformin'],
    ['Diarrhea','loperamide'],
    ['Eczema','triamcinolone'],
    ['Erectile Dysfunction','Cialis'],
    ['Gastrointestinal','Entereg'],
    ['GERD (Heartburn)','omeprazole'],
    ['Gout','allopurinol'],
    ['Hair Loss','spironolactone'],
    ['Hayfever','Zyrtec'],
    ['Herpes','acyclovir'],
    ['Hypertension','lisinopril'],
    ['Hypothyroidism','levothyroxine'],
    ['IBD (Bowel)','budesonide'],
    ['Incontinence','oxybutynin'],
    ['Insomnia','trazodone'],
    ['Menopause','esterified estrogens / methyltestosterone'],
    ['Migraine','sumatriptan'],
    ['Osteoarthritis','meloxicam'],
    ['Osteoporosis','alendronate'],
    ['Pain','tramadol'],
    ['Pneumonia','levofloxacin'],
    ['Psoriasis','clobetasol'],
    ['Rheumatoid Arthritis','methotrexate'],
    ['Schizophrenia','Seroquel'],
    ['Seizures','Keppra'],
    ['Stroke','Plavix'],
    ['Swine Flu','Tamiflu'],
    ['UTI','ciprofloxacin'],
    ['Weight Loss','phentermine']]

    command=command.lower()
    for i in range(len(database)):
        for j in range(0,len(database[i][0])):
            if command==database[i][0].lower():
                return (database[i][1])
